services:
  jekyll:
    build: .
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - .:/site
      - jekyll_bundle:/usr/local/bundle
    command: bundle exec jekyll serve --host 0.0.0.0 --port 4000 --livereload

volumes:
  jekyll_bundle: